### PR TITLE
Loading Screen Animation

### PR DESCRIPTION
**Pull request by itl7git**

### CODE REVIEW

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @itl7git, the animation looks great. Can you make the size of the animation consistent with different screen sizes, as it looks smaller on my screen:
image

**Comment by itl7git** [comment]
Ok, I'll review and set the media queries for the animation

**Comment by itl7git** [comment]
The last commit i've i set a width to the character image. With some test I have done, it fits well on diferent screens.

**Review by shubhankarval — APPROVED** [review]
Good job @itl7git!

**Pull request merged**
